name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (e.g., dev, sqa, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - DEV
          - sqa
          - prod

jobs:
  tf_fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    env:
      AWS_SECRET_ACCESS_KEY_NAME: ${{ format('AWS_SECRET_ACCESS_KEY_{0}', github.event.inputs.environment) }}
      AWS_ACCESS_KEY_ID_NAME: ${{ format('AWS_ACCESS_KEY_ID_{0}', github.event.inputs.environment) }}

    steps:
    - name: Terraform Validate
      uses: hashicorp/terraform-github-actions/validate@v0.3.7
      
    - name: Set AWS Credentials
      run: |               
         AWS_SECRET_ACCESS_KEY="${{ secrets[env.AWS_SECRET_ACCESS_KEY_NAME] }}"
         AWS_ACCESS_KEY_ID="${{ secrets[env.AWS_ACCESS_KEY_ID_NAME] }}"
        
         echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
         echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
        
    
