name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (e.g., dev, sqa, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - sqa
          - prod

jobs:
  tf_fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}      
      GITHUB_TOKEN: ${{ secrets.RUNNER_TOKEN }}
      
    steps:      
    - name: Checkout Repo
      uses: actions/checkout@v1
      
    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}
        
    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v3.0.0

    - name: Terraform init, plan and apply
      run: |
        echo `pwd`
        echo "** Running Terraform Init**"
        terraform init

        echo "** Running Terraform Validate**"
        terraform validate

        # echo "** Running Terraform Plan**"
        # terraform plan
      working-directory: iac/${{ github.event.inputs.environment }}
      
    - uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: ${{ vars.APPROVAL_LIST }}
        minimum-approvals: 1
        issue-title: "Deploying v1.0.0 to ${{ github.event.inputs.environment }}"
        issue-body: "Review the terraform plan, then approve or deny the deployment of v1.0.0 to ${{ github.event.inputs.environment }}"
        exclude-workflow-initiator-as-approver: false
        
    - name: Terraform apply
      run: |
        echo `pwd`        
        echo "** Running Terraform Plan**"
        terraform plan
      working-directory: iac/${{ github.event.inputs.environment }}
