name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (e.g., dev, sqa, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - sqa
          - prod

jobs:
  tf_fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_ACTION_WORKING_DIR: 'iac/${{ github.event.inputs.environment }}'
      GITHUB_TOKEN: ${{ secrets.RUNNER_TOKEN }}
      
    steps:
    - name: Terraform Validate
      uses: hashicorp/terraform-github-actions/validate@v0.3.7
      
    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0

    - name: Terraform Validate
      uses: hashicorp/terraform-github-actions/validate@v0.3.7

    # - uses: trstringer/manual-approval@v1
    #   with:
    #     secret: ${{ github.TOKEN }}
    #     approvers: comicalwriter
    #     minimum-approvals: 1
    #     issue-title: "Deploying v1.0.0 to ${{ github.event.inputs.environment }}"
    #     issue-body: "Review the terraform plan, then approve or deny the deployment of v1.0.0 to ${{ github.event.inputs.environment }}"
    #     exclude-workflow-initiator-as-approver: false

    - name: Terraform Plan    
      uses: hashicorp/terraform-github-actions/plan@v0.4.0
     
