name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (e.g., dev, sqa, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - sqa
          - prod

jobs:
  tf_fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    steps:
    - name: Terraform Validate
      uses: hashicorp/terraform-github-actions/validate@v0.3.7

    - uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: PoiMinhCanh, comicalwriter
        minimum-approvals: 1
        issue-title: "Deploying v1.0.0 to ${{ github.event.inputs.environment }}"
        issue-body: "Review the terraform plan, then approve or deny the deployment of v1.0.0 to ${{ github.event.inputs.environment }}"
        exclude-workflow-initiator-as-approver: false
   
